# Generated by Django 6.0 on 2025-12-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('interval', models.IntegerField(default=3600, help_text='Interval in seconds between scans')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('vulnerable', models.BooleanField(default=False)),
                ('deep_scan', models.BooleanField(default=False)),
                ('follow_links', models.BooleanField(default=False)),
                ('blind_detection', models.BooleanField(default=False)),
                ('xss_findings', models.JSONField(default=dict)),
                ('sqli_findings', models.JSONField(default=dict)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('pages_crawled', models.IntegerField(default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
